FROM python:3.9
ADD webcontroller /app 

RUN pip install poetry


COPY webcontroller/pyproject.toml webcontroller/poetry.lock ./
RUN poetry install --no-root --no-dev

COPY webcontroller ./
RUN poetry install --no-dev


ENTRYPOINT [ "poetry", "run" , "rq", "worker"]
CMD ["Extraction"]