apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: backend 
        image: ghcr.io/cs-muic/scalable-p2-scalable-t3-chocolate-charger/p2-choco-charger-backend:latest
        imagePullPolicy: Always
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom: 
            configMapKeyRef:
                name: minio-configmap
                key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
                name: minio-configmap
                key: minio-secret-key
      imagePullSecrets:
      - name: dockerconfigjson-github-com