# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   # This name uniquely identifies the PVC. Will be used in deployment below.
#   name: minio-pv-claim
#   labels:
#     app: minio-storage-claim
# spec:
#   # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     # This is the request for storage. Should be available in the cluster.
#     requests:
#       storage: 10Gi
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - minio-pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. This is used in deployment.
  name: minio-pv-claim
spec:
  # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    # The volume is mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: 10Gi