apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      env:
        - name: REDIS_HOST
          value: redis.default.svc
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""