FROM python:3.9
ADD ./app /app 
RUN pip install poetry


COPY app/pyproject.toml app/poetry.lock ./
RUN poetry install --no-root --no-dev

COPY app ./
RUN poetry install --no-dev


CMD [ "poetry", "run" , "gunicorn", "-w", "2", "--threads", "2", "-b", "0.0.0.0:5000", "app:app" ]