name: Build Backend CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: [ cs ]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Derive short SHA name
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build the Docker image of webcontroller
      run: |
        docker build . --file dockerfilecontroller \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/p2-choco-charger-backend:${{ steps.vars.outputs.sha_short }} \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/p2-choco-charger-backend:latest
    - name: Publish the images
      run: | 
        docker push ghcr.io/${{ env.BASE_IMG_NAME }}/p2-choco-charger-backend:${{ steps.vars.outputs.sha_short }}
        docker push ghcr.io/${{ env.BASE_IMG_NAME }}/p2-choco-charger-backend:latest